### PR TITLE
breaking down html in components and getting input value

### PR DESCRIPTION
**Pull request by amarie401**
@rhamilto @benjaminapetersen @sg00dwin @jgiardino

In class 06/14/2018

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Thanks @amarie401, want to resolve those conflicts or need an assist?

**Comment by amarie401** [comment]
@benjaminapetersen should be all good to go now! :D

**Comment by amarie401** [comment]
I think the only thing you may need to change is the file name for `TodoItem.js` -> will need to be `TodoItems.js` with an 's'.

**Comment by benjaminapetersen** [comment]
Excellent. merged.

**Pull request merged**
